### ISSUE TITLE
Investigate flaky Maestro scenario tests

### ISSUE THREAD

**Issue by MilenaHristova** [dotnet/arcade-services#3031] opened 2023-10-30 11:29 UTC
Some Maestro scenario tests are flaky. In the [latest arcade-services build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2303761&view=logs&j=4d9f00d7-d155-5977-7b70-2e6b79720ff2&t=b6bdfb3b-13bb-5ba7-3230-bffa36e2e1b9) there are failures in
- `Darc_GitHubFlow_NonBatched`
- `Darc_GitHubFlow_NonBatched_FailingCoherentOnlyUpdate`
- `Darc_GitHubFlow_NonBatched_StrictCoherency`
- `Darc_GitHubFlow_AutoMerge_GithubChecks_AllChecksSuccessful`

All of the failures come from `Maestro.ScenarioTests.MaestroScenarioTestBase.CheckGitHubPullRequest`:
```
Error Message:
   Maestro.ScenarioTests.MaestroTestException : Exception of type 'Maestro.ScenarioTests.MaestroTestException' was thrown.
  Stack Trace:
     at Maestro.ScenarioTests.MaestroScenarioTestBase.WaitForPullRequestAsync(String targetRepo, String targetBranch) in /_/test/Maestro.ScenarioTests/MaestroScenarioTestBase.cs:line 71
```

It seems that the method tries to find a pull request but times out

**Comment by MilenaHristova** [comment] 2023-10-30 11:33
The method is using `Octokit` to query pull requests in a repo and has 10 attempts to find one with 60s waiting between each attempt.  Increasing those attempts may help

**Comment by premun** [comment] 2023-10-30 11:41
I would not increase the timeouts. This probably means the test catches a case where the PR is not created by the Maestro service

**Comment by tkapin** [comment] 2023-10-30 11:44
Agree, although increasing timeouts is usually tempting, we need to find the root cause first as only increasing timeouts might just make things slower (and still flaky).

**Comment by premun** [comment] 2023-10-30 13:14
@MilenaHristova could you look into exceptions in App Insights during the time the E2E tests were running?

**Comment by MilenaHristova** [comment] 2023-10-30 13:15
> @MilenaHristova could you look into exceptions in App Insights during the time the E2E tests were running?

looking

**Comment by MilenaHristova** [comment] 2023-10-30 13:26
There are 2 instances of `SubscriptionActorService.SubscriptionException` : `Subscription 'df878ddb-8789-4a23-d3c4-08dbd92a6a7e' was not found...` and `Subscription '890e3ee9-b82c-434c-afe7-08dbd92a063f' was not found...` from `NonBatchedPullRequestActorImplementation` , I'll look where we are creating test subscriptions

**Comment by MilenaHristova** [comment] 2023-10-30 15:01
> There are 2 instances of `SubscriptionActorService.SubscriptionException` : `Subscription 'df878ddb-8789-4a23-d3c4-08dbd92a6a7e' was not found...` and `Subscription '890e3ee9-b82c-434c-afe7-08dbd92a063f' was not found...` from `NonBatchedPullRequestActorImplementation` , I'll look where we are creating test subscriptions. There are also a bunch of timeouts

Those errors come from `SynchronizeInProgressPullRequestAsync()` which I think is triggered by a reminder and the subscription ids don't match the ones from the failing tests  so I think it's not directly related.

**Comment by MilenaHristova** [comment] 2023-10-30 15:57
ok I found something in the traces: [query](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Fcab65fc3-d077-467d-931f-3932eabf36d3%2FresourceGroups%2Fmaestro-int-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fmaestro-int/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAAyspSkxOLVaoUSjPSC1KVSjJzE0tLknMLVBISi0pT03NU9AoyU9JLEkFSWioGxkYGesaGugaG4QYWFqZGlsZWqhr6ukp4FVjZK6uqQkAAD%252F%252FEWgAAAA%253D)

After the subscription is triggered there is a post request to `http://maestro.int-dot.net/api/webhooks/incoming/github`, seems like it returns `The 'github' WebHook receiver requires SSL/TLS in order to be secure. Register a WebHook URI of type 'https'.` 
@dkurepa how is the `webhooks/incoming/github` endpoint getting triggered?

**Comment by dkurepa** [comment] 2023-11-02 09:15
When certain events happen in GitHub, an event gets fired, and is handled by the `WebHooksController` in Maestro. The events get fired when:
- You install the app in a repo (https://docs.github.com/en/webhooks/webhook-events-and-payloads#installation, https://docs.github.com/en/webhooks/webhook-events-and-payloads#installation_repositories)
- When a test suite starts/stop (https://docs.github.com/en/webhooks/webhook-events-and-payloads#check_suite)

This app is installed in all of the product repos, so the errors can be coming from things not related to the E2E tests.

**Comment by dkurepa** [comment] 2023-11-02 09:16
The error shouldn't be appearing anymore, so if it was causing flakyness, it should be gone now

**Comment by MilenaHristova** [comment] 2023-11-10 16:36
We'll keep this open for a month or so and keep an eye on the flaky tests to see if anything changes

**Comment by andriipatsula** [comment] 2023-11-27 09:36
re-assign to @oleksandr-didyk

**Comment by oleksandr-didyk** [comment] 2023-12-01 14:35
Changes introduced by https://github.com/dotnet/arcade-services/pull/3099 and https://github.com/dotnet/arcade-services/pull/3091 have resolved the two consistently  failing tests we have seen in the past few builds.

Will re-assign to the next FR teammate to keep track of the issue

**Comment by tkapin** [comment] 2023-12-05 09:16
Re-assigning it to @andriipatsula as it's part of FR/OPS

**Comment by andriipatsula** [comment] 2023-12-06 10:31
back to @dkurepa  :)

**Comment by tkapin** [comment] 2023-12-12 09:15
Note - once this makes a full FR circle, we'll have to assign this as a project work.

**Comment by premun** [comment] 2023-12-20 14:56
So the problematic lines are these:
```
 Trigger the dependency update
 Waiting on PR to be opened in https://dev.azure.com/dnceng/internal/_git/maestro-test2
 Checking Opened PR in AzDo_BatchedTestBranch_33602ae0c000000 https://dev.azure.com/dnceng/internal/_apis/git/repositories/maestro-test2 ...
 The created pull request for maestro-test2 targeting AzDo_BatchedTestBranch_33602ae0c000000 was not updated with subsequent subscriptions after creation
```

**Comment by premun** [comment] 2023-12-20 14:58
The `AzDo_BatchedTestBranch_33602ae0c000000` branch name comes from this: `AzDo_BatchedTestBranch_{Environment.MachineName}` this is not ideal because it can contain invalid things. It can potentially also clash. It might be better to use something unique and hash it into something safe.

**Comment by premun** [comment] 2023-12-21 09:31
Putting to blocked so that we can wait out a couple of builds and see if they are OK

**Comment by premun** [comment] 2024-01-03 09:48
All green, will close this and we can re-open

**Closed by premun** 2024-01-03 09:48 UTC
Labels: Ops - First Responder
