### ISSUE TITLE
Make Maestro/Source-Build understand Directory.Packages.props

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade-services#2596] opened 2022-07-06 23:51 UTC
Now that we are doing https://github.com/dotnet/arcade/pull/9885, it would be nice to not have to have all the indirection for Versions.props for source-build and Maestro package flow.

The file format is pretty straightforward, so updating it shouldn't be particularly difficult.  We might still need Versions.props for a _few_ things (things that aren't package references).  But it seems like _preferring_ the Directory.Packages.props when it exists 

A. gives us a migration path, so everyone everywhere doesn't have to switch all at once
B. allows teams to use the feature more or less as designed for public usage and eventual IDE integration
C. leaves us an out for the occasional thing that's not _quite_ a nuget version.

I believe the two infrastructure peices we have right now that would need to understand this file are:
* Source-Build: overrides this during source build since versions numbers aren't fixed in that situration
* Maestro: flowing packages currently updates Versions.props

**Comment by premun** [comment] 2024-08-07 16:29
Duplicate of https://github.com/dotnet/arcade-services/issues/2437

**Closed by premun** 2024-08-07 16:29 UTC
